name: dropper_shop
main: com.piggest.minecraft.bukkit.dropper_shop.Dropper_shop_plugin
api-version: 1.14
version: 0.0.5
author: Pentyum
commands:
  dropper_shop:
    description: Make a dropper shop.
    usage: /<command> make ,to make a dropper shop which sell the item in you main hand.
    permission: dropper_shop.make
    permission-message: You don't have permission
  depository:
    description: commands relate to depository.
    usage: /<command> make ,to make a depository.
    permission: depository.make
    permission-message: You don't have permission
  grinder:
    description: commands relate to grinder.
    usage: /<command> make ,to make a grinder.
    permission: grinder.make
    permission-message: You don't have permission
  adv_furnace:
    description: commands relate to advanced furnace.
    usage: /<command> make ,to make a advanced furnace.
    permission: adv_furnace.make
    permission-message: You don't have permission
  wrench:
    description: commands relate to wrench.
    usage: /<command> to see the plugin info or /<command> setprice [world] to change price.
    permission: wrench.use
    permission-message: You don't have permission
  exp_saver:
    description: commands relate to exp_saver.
    usage: /<command> remove to remove a exp saver.
    permission: exp_saver.use
    permission-message: You don't have permission
  lottery:
    description: commands relate to lottery pool.
    usage: /<command> possibility to set the possibility of the item in your hand.
    permission: lottery.use
    permission-message: You don't have permission
permissions:
  dropper_shop.*:
    description: Gives access to all dropper shop commands.
    default: op
  dropper_shop.make:
    description: Gives access to make dropper shop.
    default: true
  dropper_shop.changeprice:
    description: Change price dropper shop.
    default: op
  dropper_shop.unexplodable:
    description: Make unexplodable shop.
    default: op
  dropper_shop.remove:
    description: Remove dropper shop.
    default: true
  dropper_shop.remove.others:
    description: Remove others dropper shop.
    default: op
  depository.make:
    description: Make or remove a depository.
    default: true
  depository.connect:
    description: Make a reader connect to a depository.
    default: true
  depository.input:
    description: Input itemstack to a depository.
    default: true
  depository.output:
    description: Get itemstack from a depository.
    default: true
  depository.god:
    description: Change info.
    default: op
  grinder.make:
    description: Make or remove a grinder.
    default: true
  adv_furnace.make:
    description: Make or remove a advanced furnace.
    default: true
  wrench.*:
    description: Gives access to all wrench commands
    default: op
  wrench.use:
    description: Gives access to use wrench
    default: true
  wrench.changeprice:
    description: change wrench price
    default: op
  exp_saver.*:
    description: Gives access to all wrench commands
    default: op
  exp_saver.use:
    description: Gives access to use exp_saver
    default: true
  lottery.*:
    description: Gives access to all lottery pool commands.
    default: op
  lottery.use:
    description: Use lottery pool.
    default: true
  lottery.set:
    description: Set lottery pool.
    default: op
softdepend: [Vault]